POST localhost:8080/events
content-type: application/jsonDateTime
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBydWVzYmEyQGdtYWlsLmNvbSIsImV4cCI6MTcxODEzNTMzMiwidXNlcklkIjozfQ.1u7axmNAi3L7B53oQVQTfrIyjLZ0EPJi3Kn7zzGZyXg

{
  "Name": "Event new",
  "Description": "Event new",
  "DateTime": "2021-12-31T23:59:59.000Z",
  "Location": "Event new location"
}

