PUT localhost:8080/events/1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBydWVzYmEyQGdtYWlsLmNvbSIsImV4cCI6MTcxODEzNjc0NSwidXNlcklkIjozfQ.JdDv-FHcg8ArvpIgYhS4XK-I6S-JX9f1gDT4sG80c6w

{
  "Name": "Event updated!",
  "Description": "Event 1 description",
  "DateTime": "2021-12-31T23:59:59.000Z",
  "Location": "Event 1 location"
}